// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using linksy_backend_api.Models;

#nullable disable

namespace linksy_backend_api.Infrastructure.Migrations
{
    [DbContext(typeof(LinksyDbContext))]
    partial class LinksyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.CallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("video")
                        .HasColumnName("call_type");

                    b.Property<Guid>("CallerId")
                        .HasColumnType("uuid")
                        .HasColumnName("caller_id");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ringing")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CallerId", "StartedAt")
                        .HasDatabaseName("ix_call_logs_caller_id_started_at");

                    b.HasIndex("ChatroomId", "StartedAt")
                        .HasDatabaseName("ix_call_logs_chatroom_id_started_at");

                    b.ToTable("call_logs", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.CallParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CallLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_log_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("invited")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CallLogId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_call_participants_call_log_id_user_id");

                    b.ToTable("call_participants", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MemberPermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<bool>("CanDeleteMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_delete_messages");

                    b.Property<bool>("CanEditGroupInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_edit_group_info");

                    b.Property<bool>("CanInviteMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_invite_members");

                    b.Property<bool>("CanManageCalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_manage_calls");

                    b.Property<bool>("CanPinMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_pin_messages");

                    b.Property<bool>("CanRemoveMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_remove_members");

                    b.Property<bool>("CanSendFiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_send_files");

                    b.Property<bool>("CanSendMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_send_media");

                    b.Property<bool>("CanSendMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_send_messages");

                    b.Property<bool>("CanSendVoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_send_voice");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PermissionId")
                        .HasName("permission_members_pkey");

                    b.HasIndex(new[] { "MemberId" }, "permission_members_member_id_idx")
                        .IsUnique();

                    b.ToTable("member_permissions", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageAttachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("attachment_type");

                    b.Property<string>("CdnUrl")
                        .HasColumnType("text")
                        .HasColumnName("cdn_url");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("FileName")
                        .HasColumnType("character varying")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .HasColumnType("character varying")
                        .HasColumnName("mime_type");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("AttachmentId")
                        .HasName("message_attachments_pkey");

                    b.HasIndex(new[] { "MessageId", "AttachmentType" }, "message_attachments_message_id_attachment_type_idx");

                    b.HasIndex(new[] { "MessageId" }, "message_attachments_message_id_idx");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageDelivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'sent'::character varying");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeliveryId")
                        .HasName("message_deliveries_pkey");

                    b.HasIndex(new[] { "MessageId", "Status" }, "message_deliveries_message_id_status_idx");

                    b.HasIndex(new[] { "MessageId", "UserId" }, "message_deliveries_message_id_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "Status", "ReadAt" }, "message_deliveries_user_id_status_read_at_idx");

                    b.ToTable("message_deliveries", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageMention", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("MentionedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentioned_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId", "MentionedUserId")
                        .HasName("message_mentions_pkey");

                    b.HasIndex(new[] { "MentionedUserId" }, "message_mentions_mentioned_user_id_idx");

                    b.HasIndex(new[] { "MessageId" }, "message_mentions_message_id_idx");

                    b.ToTable("message_mentions", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.PinnedMessage", b =>
                {
                    b.Property<Guid>("PinnedMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("pinned_message_id");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("PinnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PinnedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("pinned_by_user_id");

                    b.HasKey("PinnedMessageId")
                        .HasName("pinned_messages_pkey");

                    b.HasIndex(new[] { "ChatroomId", "MessageId" }, "pinned_messages_chatroom_id_message_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ChatroomId", "PinnedAt" }, "pinned_messages_chatroom_id_pinned_at_idx");

                    b.HasIndex(new[] { "MessageId" }, "pinned_messages_message_id_idx");

                    b.ToTable("pinned_messages", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePoll", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_closed");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("question");

                    b.HasKey("MessageId")
                        .HasName("message_polls_pkey");

                    b.ToTable("message_polls", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePollOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("text");

                    b.HasKey("OptionId")
                        .HasName("message_poll_options_pkey");

                    b.HasIndex(new[] { "MessageId" }, "message_poll_options_message_id_idx");

                    b.HasIndex(new[] { "MessageId", "SortOrder" }, "message_poll_options_message_id_sort_order_idx");

                    b.ToTable("message_poll_options", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePollVote", b =>
                {
                    b.Property<Guid>("VoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("vote_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voted_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("VoteId")
                        .HasName("message_poll_votes_pkey");

                    b.HasIndex(new[] { "MessageId", "UserId" }, "message_poll_votes_message_id_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "OptionId" }, "message_poll_votes_option_id_idx");

                    b.ToTable("message_poll_votes", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageReaction", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reaction_id");

                    b.Property<string>("EmojiCode")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("emoji_code");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ReactedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reacted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ReactionId")
                        .HasName("message_reactions_pkey");

                    b.HasIndex(new[] { "MessageId", "EmojiCode" }, "message_reactions_message_id_emoji_code_idx");

                    b.HasIndex(new[] { "MessageId", "UserId", "EmojiCode" }, "message_reactions_message_id_user_id_emoji_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "ReactedAt" }, "message_reactions_user_id_reacted_at_idx");

                    b.ToTable("message_reactions", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_notifications");

                    b.Property<bool>("MessagePreviewEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("message_preview_enabled");

                    b.Property<bool>("NotificationSoundEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notification_sound_enabled");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notification_settings_pkey");

                    b.HasIndex(new[] { "UserId" }, "notification_settings_user_id_key")
                        .IsUnique();

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.PrivacySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("LastSeenEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("last_seen_enabled");

                    b.Property<string>("ProfilePhotoVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("profile_photo_visibility")
                        .HasDefaultValueSql("'everyone'::character varying");

                    b.Property<bool>("ReadReceiptsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("read_receipts_enabled");

                    b.Property<string>("StatusVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status_visibility")
                        .HasDefaultValueSql("'everyone'::character varying");

                    b.Property<bool>("TypingIndicatorsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("typing_indicators_enabled");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WhoCanAddToGroups")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("who_can_add_to_groups")
                        .HasDefaultValueSql("'everyone'::character varying");

                    b.HasKey("Id")
                        .HasName("privacy_settings_pkey");

                    b.HasIndex(new[] { "UserId" }, "privacy_settings_user_id_key")
                        .IsUnique();

                    b.ToTable("privacy_settings", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.UserSettings", b =>
                {
                    b.Property<Guid>("SettingId")
                        .HasColumnType("uuid")
                        .HasColumnName("setting_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("language")
                        .HasDefaultValueSql("'vi'::character varying");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("theme")
                        .HasDefaultValueSql("'system'::character varying");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("timezone")
                        .HasDefaultValueSql("'Asia/Ho_Chi_Minh'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SettingId")
                        .HasName("user_settings_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_settings_user_id_key")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.UserStatus", b =>
                {
                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("CustomStatus")
                        .HasColumnType("character varying")
                        .HasColumnName("custom_status");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status_type")
                        .HasDefaultValueSql("'offline'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("StatusId")
                        .HasName("user_status_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_status_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "StatusType" }, "user_status_user_id_status_type_idx");

                    b.ToTable("user_status", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.AccessToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("access_tokens_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "access_tokens_expires_at_idx");

                    b.HasIndex(new[] { "Token" }, "access_tokens_token_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "Token" }, "access_tokens_token_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "access_tokens_user_id_idx");

                    b.ToTable("access_tokens", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.BlockedUser", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<DateTime?>("BlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_user_id");

                    b.Property<Guid>("BlockerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_user_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("BlockId")
                        .HasName("blocked_users_pkey");

                    b.HasIndex(new[] { "BlockedUserId", "BlockerUserId" }, "blocked_users_blocked_user_id_blocker_user_id_idx");

                    b.HasIndex(new[] { "BlockerUserId", "BlockedAt" }, "blocked_users_blocker_user_id_blocked_at_idx");

                    b.HasIndex(new[] { "BlockerUserId", "BlockedUserId" }, "blocked_users_blocker_user_id_blocked_user_id_idx")
                        .IsUnique();

                    b.ToTable("blocked_users", null, t =>
                        {
                            t.HasComment("CHECK (blocker_user_id != blocked_user_id)");
                        });
                });

            modelBuilder.Entity("linksy_backend_api.Models.Chatroom", b =>
                {
                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<string>("RoomName")
                        .HasColumnType("character varying")
                        .HasColumnName("room_name");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("room_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ChatroomId")
                        .HasName("chatrooms_pkey");

                    b.HasIndex("LastMessageId");

                    b.HasIndex(new[] { "CreatedBy", "RoomType" }, "chatrooms_created_by_room_type_idx");

                    b.HasIndex(new[] { "IsArchived", "LastActivityAt" }, "chatrooms_is_archived_last_activity_at_idx");

                    b.HasIndex(new[] { "LastActivityAt" }, "chatrooms_last_activity_at_idx");

                    b.HasIndex(new[] { "RoomType", "IsActive", "LastActivityAt" }, "chatrooms_room_type_is_active_last_activity_at_idx");

                    b.ToTable("chatrooms", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.ChatroomMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<bool?>("IsMuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_muted");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("member_role")
                        .HasDefaultValueSql("'member'::character varying");

                    b.Property<int?>("MessageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("message_count");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("muted_until");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("nickname");

                    b.Property<string>("NotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("notification_preference")
                        .HasDefaultValueSql("'all::character varying");

                    b.Property<Guid?>("RemovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("removed_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MemberId")
                        .HasName("chatroom_members_pkey");

                    b.HasIndex("AddedBy");

                    b.HasIndex("RemovedBy");

                    b.HasIndex(new[] { "ChatroomId", "LastReadAt" }, "chatroom_members_chatroom_id_last_read_at_idx");

                    b.HasIndex(new[] { "ChatroomId", "MemberRole" }, "chatroom_members_chatroom_id_member_role_idx");

                    b.HasIndex(new[] { "ChatroomId", "UserId" }, "chatroom_members_chatroom_id_user_id_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "ChatroomId" }, "chatroom_members_user_id_chatroom_id_idx");

                    b.HasIndex(new[] { "UserId", "LeftAt" }, "chatroom_members_user_id_left_at_idx");

                    b.ToTable("chatroom_members", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.EmailOtp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_expired");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<int?>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("otp_code");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("email_otps_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "email_otps_created_at_idx");

                    b.HasIndex(new[] { "Email", "OtpCode", "IsUsed", "IsExpired" }, "email_otps_email_otp_code_is_used_is_expired_idx");

                    b.HasIndex(new[] { "ExpiresAt" }, "email_otps_expires_at_idx");

                    b.HasIndex(new[] { "UserId", "Purpose" }, "email_otps_user_id_purpose_idx");

                    b.ToTable("email_otps", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.HasKey("RequestId")
                        .HasName("friend_requests_pkey");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("friend_requests_sent_at_idx");

                    b.HasIndex("ReceiverId", "Status")
                        .HasDatabaseName("friend_requests_receiver_id_status_idx");

                    b.HasIndex("SenderId", "Status")
                        .HasDatabaseName("friend_requests_sender_id_status_idx");

                    b.ToTable("friend_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_FriendRequests_DifferentUsers", "sender_id != receiver_id");

                            t.HasCheckConstraint("CK_FriendRequests_Status", "status IN ('pending', 'accepted', 'rejected', 'cancelled')");
                        });
                });

            modelBuilder.Entity("linksy_backend_api.Models.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("friendship_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user1_id");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user2_id");

                    b.HasKey("FriendshipId")
                        .HasName("friendships_pkey");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("friendships_created_at_idx");

                    b.HasIndex("User1Id")
                        .HasDatabaseName("friendships_user1_id_idx");

                    b.HasIndex("User2Id")
                        .HasDatabaseName("friendships_user2_id_idx");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique()
                        .HasDatabaseName("friendships_user1_id_user2_id_key");

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Friendships_DifferentUsers", "user1_id != user2_id");
                        });
                });

            modelBuilder.Entity("linksy_backend_api.Models.GroupInvitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<string>("Message")
                        .HasColumnType("character varying")
                        .HasColumnName("message");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.HasKey("InvitationId")
                        .HasName("group_invitations_pkey");

                    b.HasIndex("InvitedBy");

                    b.HasIndex(new[] { "ChatroomId", "InvitedUserId", "Status" }, "group_invitations_chatroom_id_invited_user_id_status_idx");

                    b.HasIndex(new[] { "ChatroomId", "Status" }, "group_invitations_chatroom_id_status_idx");

                    b.HasIndex(new[] { "ExpiresAt" }, "group_invitations_expires_at_idx");

                    b.HasIndex(new[] { "InvitedUserId", "Status", "SentAt" }, "group_invitations_invited_user_id_status_sent_at_idx");

                    b.ToTable("group_invitations", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_edited");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_message_id");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId")
                        .HasName("messages_pkey");

                    b.HasIndex(new[] { "ChatroomId", "IsDeleted", "SentAt" }, "messages_chatroom_id_is_deleted_sent_at_idx");

                    b.HasIndex(new[] { "ChatroomId", "SentAt" }, "messages_chatroom_id_sent_at_idx");

                    b.HasIndex(new[] { "MessageType", "ChatroomId" }, "messages_message_type_chatroom_id_idx");

                    b.HasIndex(new[] { "ParentMessageId", "SentAt" }, "messages_parent_message_id_sent_at_idx");

                    b.HasIndex(new[] { "SenderId", "SentAt" }, "messages_sender_id_sent_at_idx");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("action_url");

                    b.Property<string>("Body")
                        .HasColumnType("character varying")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("character varying")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "notifications_created_at_idx");

                    b.HasIndex(new[] { "RelatedEntityType", "RelatedEntityId" }, "notifications_related_entity_type_related_entity_id_idx");

                    b.HasIndex(new[] { "UserId", "IsRead", "IsDeleted", "CreatedAt" }, "notifications_user_id_is_read_is_deleted_created_at_idx");

                    b.HasIndex(new[] { "UserId", "NotificationType", "CreatedAt" }, "notifications_user_id_notification_type_created_at_idx");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "roles_role_name_idx");

                    b.HasIndex(new[] { "RoleName" }, "roles_role_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("AccountLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_locked_until");

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasColumnType("character varying")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int?>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("Fullname")
                        .HasColumnType("character varying")
                        .HasColumnName("fullname");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_idx");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "IsActive", "CreatedAt" }, "users_is_active_created_at_idx");

                    b.HasIndex(new[] { "LastLoginAt" }, "users_last_login_at_idx");

                    b.HasIndex(new[] { "Username" }, "users_username_idx");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "RoleId" }, "user_roles_role_id_idx");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "user_roles_user_id_role_id_idx")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.CallLog", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "Caller")
                        .WithMany()
                        .HasForeignKey("CallerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany()
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caller");

                    b.Navigation("Chatroom");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.CallParticipant", b =>
                {
                    b.HasOne("linksy_backend_api.Domain.Entities.Models.CallLog", "CallLog")
                        .WithMany("Participants")
                        .HasForeignKey("CallLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CallLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MemberPermission", b =>
                {
                    b.HasOne("linksy_backend_api.Models.ChatroomMember", "Member")
                        .WithOne("MemberPermission")
                        .HasForeignKey("linksy_backend_api.Domain.Entities.Models.MemberPermission", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("permission_members_member_id_fkey");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageAttachment", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Message", "Message")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_attachments_message_id_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageDelivery", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Message", "Message")
                        .WithMany("MessageDeliveries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_deliveries_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("MessageDeliveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_deliveries_user_id_fkey");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageMention", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Message", "Message")
                        .WithMany("MessageMentions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_mentions_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "MentionedUser")
                        .WithMany("MessageMentions")
                        .HasForeignKey("MentionedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_mentions_mentioned_user_id_fkey");

                    b.Navigation("Message");

                    b.Navigation("MentionedUser");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.PinnedMessage", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pinned_messages_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.Message", "Message")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pinned_messages_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "PinnedByUser")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("PinnedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pinned_messages_pinned_by_user_id_fkey");

                    b.Navigation("Chatroom");

                    b.Navigation("Message");

                    b.Navigation("PinnedByUser");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePoll", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_polls_created_by_user_id_fkey");

                    b.HasOne("linksy_backend_api.Models.Message", "Message")
                        .WithOne("Poll")
                        .HasForeignKey("linksy_backend_api.Domain.Entities.Models.MessagePoll", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_polls_message_id_fkey");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePollOption", b =>
                {
                    b.HasOne("linksy_backend_api.Domain.Entities.Models.MessagePoll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_poll_options_message_id_fkey");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePollVote", b =>
                {
                    b.HasOne("linksy_backend_api.Domain.Entities.Models.MessagePollOption", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_poll_votes_option_id_fkey");

                    b.HasOne("linksy_backend_api.Domain.Entities.Models.MessagePoll", "Poll")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_poll_votes_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_poll_votes_user_id_fkey");

                    b.Navigation("Option");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessageReaction", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Message", "Message")
                        .WithMany("MessageReactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_reactions_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("MessageReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_reactions_user_id_fkey");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.NotificationSettings", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("linksy_backend_api.Domain.Entities.Models.NotificationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notification_settings_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.PrivacySettings", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithOne("PrivacySettings")
                        .HasForeignKey("linksy_backend_api.Domain.Entities.Models.PrivacySettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("privacy_settings_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.UserSettings", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("linksy_backend_api.Domain.Entities.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_settings_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.UserStatus", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithOne("UserStatus")
                        .HasForeignKey("linksy_backend_api.Domain.Entities.Models.UserStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_status_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.AccessToken", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("AccessTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("access_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.BlockedUser", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "BlockedUserNavigation")
                        .WithMany("BlockedUserBlockedUserNavigations")
                        .HasForeignKey("BlockedUserId")
                        .IsRequired()
                        .HasConstraintName("blocked_users_blocked_user_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "BlockerUser")
                        .WithMany("BlockedUserBlockerUsers")
                        .HasForeignKey("BlockerUserId")
                        .IsRequired()
                        .HasConstraintName("blocked_users_blocker_user_id_fkey");

                    b.Navigation("BlockedUserNavigation");

                    b.Navigation("BlockerUser");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Chatroom", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "CreatedByNavigation")
                        .WithMany("Chatrooms")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("chatrooms_created_by_fkey");

                    b.HasOne("linksy_backend_api.Models.Message", "LastMessage")
                        .WithMany("Chatrooms")
                        .HasForeignKey("LastMessageId")
                        .HasConstraintName("chatrooms_last_message_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("LastMessage");
                });

            modelBuilder.Entity("linksy_backend_api.Models.ChatroomMember", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "AddedByNavigation")
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("chatroom_members_added_by_fkey");

                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("ChatroomMembers")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatroom_members_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "RemovedByNavigation")
                        .WithMany()
                        .HasForeignKey("RemovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("chatroom_members_removed_by_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("ChatroomMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatroom_members_user_id_fkey");

                    b.Navigation("AddedByNavigation");

                    b.Navigation("Chatroom");

                    b.Navigation("RemovedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.EmailOtp", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("EmailOtps")
                        .HasForeignKey("UserId")
                        .HasConstraintName("email_otps_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.FriendRequest", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friend_requests_receiver_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "Sender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friend_requests_sender_id_fkey");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Friendship", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User1")
                        .WithMany("FriendshipUser1s")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friendships_user1_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User2")
                        .WithMany("FriendshipUser2s")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friendships_user2_id_fkey");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("linksy_backend_api.Models.GroupInvitation", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("ChatroomId")
                        .IsRequired()
                        .HasConstraintName("group_invitations_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "InvitedByNavigation")
                        .WithMany("GroupInvitationInvitedByNavigations")
                        .HasForeignKey("InvitedBy")
                        .IsRequired()
                        .HasConstraintName("group_invitations_invited_by_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "InvitedUser")
                        .WithMany("GroupInvitationInvitedUsers")
                        .HasForeignKey("InvitedUserId")
                        .IsRequired()
                        .HasConstraintName("group_invitations_invited_user_id_fkey");

                    b.Navigation("Chatroom");

                    b.Navigation("InvitedByNavigation");

                    b.Navigation("InvitedUser");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Message", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatroomId")
                        .IsRequired()
                        .HasConstraintName("messages_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.Message", "ParentMessage")
                        .WithMany("InverseParentMessage")
                        .HasForeignKey("ParentMessageId")
                        .HasConstraintName("messages_parent_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("messages_sender_id_fkey");

                    b.Navigation("Chatroom");

                    b.Navigation("ParentMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Notification", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.UserRole", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.CallLog", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Chatroom", b =>
                {
                    b.Navigation("ChatroomMembers");

                    b.Navigation("GroupInvitations");

                    b.Navigation("Messages");

                    b.Navigation("PinnedMessages");
                });

            modelBuilder.Entity("linksy_backend_api.Models.ChatroomMember", b =>
                {
                    b.Navigation("MemberPermission");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePoll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("linksy_backend_api.Domain.Entities.Models.MessagePollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Message", b =>
                {
                    b.Navigation("Chatrooms");

                    b.Navigation("InverseParentMessage");

                    b.Navigation("MessageAttachments");

                    b.Navigation("MessageDeliveries");

                    b.Navigation("MessageMentions");

                    b.Navigation("MessageReactions");

                    b.Navigation("PinnedMessages");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("linksy_backend_api.Models.User", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("BlockedUserBlockedUserNavigations");

                    b.Navigation("BlockedUserBlockerUsers");

                    b.Navigation("ChatroomMembers");

                    b.Navigation("Chatrooms");

                    b.Navigation("EmailOtps");

                    b.Navigation("FriendshipUser1s");

                    b.Navigation("FriendshipUser2s");

                    b.Navigation("GroupInvitationInvitedByNavigations");

                    b.Navigation("GroupInvitationInvitedUsers");

                    b.Navigation("MessageDeliveries");

                    b.Navigation("MessageMentions");

                    b.Navigation("MessageReactions");

                    b.Navigation("Messages");

                    b.Navigation("PinnedMessages");

                    b.Navigation("NotificationSettings");

                    b.Navigation("Notifications");

                    b.Navigation("PrivacySettings");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSettings");

                    b.Navigation("UserStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
