// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using linksy_backend_api.Models;

#nullable disable

namespace linksy_backend_api.Infrastructure.Migrations
{
    [DbContext(typeof(LinksyDbContext))]
    partial class LinksyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("linksy_backend_api.Models.AccessToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("access_tokens_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "access_tokens_expires_at_idx");

                    b.HasIndex(new[] { "Token" }, "access_tokens_token_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "Token" }, "access_tokens_token_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "access_tokens_user_id_idx");

                    b.ToTable("access_tokens", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.BlockedUser", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<DateTime?>("BlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_user_id");

                    b.Property<Guid>("BlockerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_user_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("BlockId")
                        .HasName("blocked_users_pkey");

                    b.HasIndex(new[] { "BlockedUserId", "BlockerUserId" }, "blocked_users_blocked_user_id_blocker_user_id_idx");

                    b.HasIndex(new[] { "BlockerUserId", "BlockedAt" }, "blocked_users_blocker_user_id_blocked_at_idx");

                    b.HasIndex(new[] { "BlockerUserId", "BlockedUserId" }, "blocked_users_blocker_user_id_blocked_user_id_idx")
                        .IsUnique();

                    b.ToTable("blocked_users", null, t =>
                        {
                            t.HasComment("CHECK (blocker_user_id != blocked_user_id)");
                        });
                });

            modelBuilder.Entity("linksy_backend_api.Models.Chatroom", b =>
                {
                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<string>("RoomName")
                        .HasColumnType("character varying")
                        .HasColumnName("room_name");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("room_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ChatroomId")
                        .HasName("chatrooms_pkey");

                    b.HasIndex("LastMessageId");

                    b.HasIndex(new[] { "CreatedBy", "RoomType" }, "chatrooms_created_by_room_type_idx");

                    b.HasIndex(new[] { "IsArchived", "LastActivityAt" }, "chatrooms_is_archived_last_activity_at_idx");

                    b.HasIndex(new[] { "LastActivityAt" }, "chatrooms_last_activity_at_idx");

                    b.HasIndex(new[] { "RoomType", "IsActive", "LastActivityAt" }, "chatrooms_room_type_is_active_last_activity_at_idx");

                    b.ToTable("chatrooms", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.EmailOtp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_expired");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<int?>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("otp_code");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("email_otps_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "email_otps_created_at_idx");

                    b.HasIndex(new[] { "Email", "OtpCode", "IsUsed", "IsExpired" }, "email_otps_email_otp_code_is_used_is_expired_idx");

                    b.HasIndex(new[] { "ExpiresAt" }, "email_otps_expires_at_idx");

                    b.HasIndex(new[] { "UserId", "Purpose" }, "email_otps_user_id_purpose_idx");

                    b.ToTable("email_otps", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.HasKey("RequestId")
                        .HasName("friend_requests_pkey");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("friend_requests_sent_at_idx");

                    b.HasIndex("ReceiverId", "Status")
                        .HasDatabaseName("friend_requests_receiver_id_status_idx");

                    b.HasIndex("SenderId", "Status")
                        .HasDatabaseName("friend_requests_sender_id_status_idx");

                    b.ToTable("friend_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_FriendRequests_DifferentUsers", "sender_id != receiver_id");

                            t.HasCheckConstraint("CK_FriendRequests_Status", "status IN ('pending', 'accepted', 'rejected', 'cancelled')");
                        });
                });

            modelBuilder.Entity("linksy_backend_api.Models.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("friendship_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user1_id");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user2_id");

                    b.HasKey("FriendshipId")
                        .HasName("friendships_pkey");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("friendships_created_at_idx");

                    b.HasIndex("User1Id")
                        .HasDatabaseName("friendships_user1_id_idx");

                    b.HasIndex("User2Id")
                        .HasDatabaseName("friendships_user2_id_idx");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique()
                        .HasDatabaseName("friendships_user1_id_user2_id_key");

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Friendships_DifferentUsers", "user1_id != user2_id");
                        });
                });

            modelBuilder.Entity("linksy_backend_api.Models.GroupInvitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<string>("Message")
                        .HasColumnType("character varying")
                        .HasColumnName("message");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.HasKey("InvitationId")
                        .HasName("group_invitations_pkey");

                    b.HasIndex("InvitedBy");

                    b.HasIndex(new[] { "ChatroomId", "InvitedUserId", "Status" }, "group_invitations_chatroom_id_invited_user_id_status_idx");

                    b.HasIndex(new[] { "ChatroomId", "Status" }, "group_invitations_chatroom_id_status_idx");

                    b.HasIndex(new[] { "ExpiresAt" }, "group_invitations_expires_at_idx");

                    b.HasIndex(new[] { "InvitedUserId", "Status", "SentAt" }, "group_invitations_invited_user_id_status_sent_at_idx");

                    b.ToTable("group_invitations", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_edited");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_message_id");

                    b.Property<int?>("ReplyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reply_count");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId")
                        .HasName("messages_pkey");

                    b.HasIndex(new[] { "ChatroomId", "IsDeleted", "SentAt" }, "messages_chatroom_id_is_deleted_sent_at_idx");

                    b.HasIndex(new[] { "ChatroomId", "SentAt" }, "messages_chatroom_id_sent_at_idx");

                    b.HasIndex(new[] { "MessageType", "ChatroomId" }, "messages_message_type_chatroom_id_idx");

                    b.HasIndex(new[] { "ParentMessageId", "SentAt" }, "messages_parent_message_id_sent_at_idx");

                    b.HasIndex(new[] { "SenderId", "SentAt" }, "messages_sender_id_sent_at_idx");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("action_url");

                    b.Property<string>("Body")
                        .HasColumnType("character varying")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("character varying")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "notifications_created_at_idx");

                    b.HasIndex(new[] { "RelatedEntityType", "RelatedEntityId" }, "notifications_related_entity_type_related_entity_id_idx");

                    b.HasIndex(new[] { "UserId", "IsRead", "IsDeleted", "CreatedAt" }, "notifications_user_id_is_read_is_deleted_created_at_idx");

                    b.HasIndex(new[] { "UserId", "NotificationType", "CreatedAt" }, "notifications_user_id_notification_type_created_at_idx");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "roles_role_name_idx");

                    b.HasIndex(new[] { "RoleName" }, "roles_role_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.ChatroomMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<bool?>("CanDeleteMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_delete_messages");

                    b.Property<bool?>("CanEditGroupInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_edit_group_info");

                    b.Property<bool?>("CanInviteMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_invite_members");

                    b.Property<bool?>("CanRemoveMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_remove_members");

                    b.Property<bool?>("CanSendMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_send_message");

                    b.Property<Guid>("ChatroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatroom_id");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("member_role")
                        .HasDefaultValueSql("'member'::character varying");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MemberId")
                        .HasName("role_members_pkey");

                    b.HasIndex(new[] { "ChatroomId", "MemberRole" }, "role_members_chatroom_id_member_role_idx");

                    b.HasIndex(new[] { "ChatroomId", "UserId" }, "role_members_chatroom_id_user_id_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "ChatroomId" }, "role_members_user_id_chatroom_id_idx");

                    b.HasIndex(new[] { "UserId", "LeftAt" }, "role_members_user_id_left_at_idx");

                    b.ToTable("role_members", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("AccountLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_locked_until");

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasColumnType("character varying")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int?>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("Fullname")
                        .HasColumnType("character varying")
                        .HasColumnName("fullname");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_idx");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "IsActive", "CreatedAt" }, "users_is_active_created_at_idx");

                    b.HasIndex(new[] { "LastLoginAt" }, "users_last_login_at_idx");

                    b.HasIndex(new[] { "Username" }, "users_username_idx");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "RoleId" }, "user_roles_role_id_idx");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "user_roles_user_id_role_id_idx")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("linksy_backend_api.Models.AccessToken", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("AccessTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("access_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.BlockedUser", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "BlockedUserNavigation")
                        .WithMany("BlockedUserBlockedUserNavigations")
                        .HasForeignKey("BlockedUserId")
                        .IsRequired()
                        .HasConstraintName("blocked_users_blocked_user_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "BlockerUser")
                        .WithMany("BlockedUserBlockerUsers")
                        .HasForeignKey("BlockerUserId")
                        .IsRequired()
                        .HasConstraintName("blocked_users_blocker_user_id_fkey");

                    b.Navigation("BlockedUserNavigation");

                    b.Navigation("BlockerUser");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Chatroom", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "CreatedByNavigation")
                        .WithMany("Chatrooms")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("chatrooms_created_by_fkey");

                    b.HasOne("linksy_backend_api.Models.Message", "LastMessage")
                        .WithMany("Chatrooms")
                        .HasForeignKey("LastMessageId")
                        .HasConstraintName("chatrooms_last_message_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("LastMessage");
                });

            modelBuilder.Entity("linksy_backend_api.Models.EmailOtp", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("EmailOtps")
                        .HasForeignKey("UserId")
                        .HasConstraintName("email_otps_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.FriendRequest", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friend_requests_receiver_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "Sender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friend_requests_sender_id_fkey");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Friendship", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User1")
                        .WithMany("FriendshipUser1s")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friendships_user1_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User2")
                        .WithMany("FriendshipUser2s")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friendships_user2_id_fkey");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("linksy_backend_api.Models.GroupInvitation", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("ChatroomId")
                        .IsRequired()
                        .HasConstraintName("group_invitations_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "InvitedByNavigation")
                        .WithMany("GroupInvitationInvitedByNavigations")
                        .HasForeignKey("InvitedBy")
                        .IsRequired()
                        .HasConstraintName("group_invitations_invited_by_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "InvitedUser")
                        .WithMany("GroupInvitationInvitedUsers")
                        .HasForeignKey("InvitedUserId")
                        .IsRequired()
                        .HasConstraintName("group_invitations_invited_user_id_fkey");

                    b.Navigation("Chatroom");

                    b.Navigation("InvitedByNavigation");

                    b.Navigation("InvitedUser");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Message", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatroomId")
                        .IsRequired()
                        .HasConstraintName("messages_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.Message", "ParentMessage")
                        .WithMany("InverseParentMessage")
                        .HasForeignKey("ParentMessageId")
                        .HasConstraintName("messages_parent_message_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("messages_sender_id_fkey");

                    b.Navigation("Chatroom");

                    b.Navigation("ParentMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Notification", b =>
                {
                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.ChatroomMember", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Chatroom", "Chatroom")
                        .WithMany("ChatroomMembers")
                        .HasForeignKey("ChatroomId")
                        .IsRequired()
                        .HasConstraintName("role_members_chatroom_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("ChatroomMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("role_members_user_id_fkey");

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.UserRole", b =>
                {
                    b.HasOne("linksy_backend_api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("linksy_backend_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Chatroom", b =>
                {
                    b.Navigation("GroupInvitations");

                    b.Navigation("Messages");

                    b.Navigation("ChatroomMembers");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Message", b =>
                {
                    b.Navigation("Chatrooms");

                    b.Navigation("InverseParentMessage");
                });

            modelBuilder.Entity("linksy_backend_api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("linksy_backend_api.Models.User", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("BlockedUserBlockedUserNavigations");

                    b.Navigation("BlockedUserBlockerUsers");

                    b.Navigation("Chatrooms");

                    b.Navigation("EmailOtps");

                    b.Navigation("FriendshipUser1s");

                    b.Navigation("FriendshipUser2s");

                    b.Navigation("GroupInvitationInvitedByNavigations");

                    b.Navigation("GroupInvitationInvitedUsers");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("ChatroomMembers");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
